In [90]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
from datetime import datetime
import re
import fitz  # PyMuPDF
from io import BytesIO

In [4]:
# def fetch_and_append_content_from_csv(csv_file_path):
#     # Read the CSV
#     df = pd.read_csv(csv_file_path)

#     # Get current and previous month/year
#     now = datetime.now()
#     prev_month = (now.month - 1) if now.month > 1 else 12
#     prev_year = now.year if now.month > 1 else now.year - 1
#     prev_month_str = f"{prev_month:02d}"
#     prev_year_str = str(prev_year)

#     contents = []

#     for url in df['blogs-href']:
#         match = re.search(r'/(\d{4})/(\d{2})/', str(url))
#         if match:
#             year, month = match.groups()
#             if year == prev_year_str and month == prev_month_str:
#                 try:
#                     response = requests.get(url, timeout=100)
#                     soup = BeautifulSoup(response.content, "html.parser")
#                     text = soup.get_text(separator=" ", strip=True)
#                     contents.append(text)
#                 except Exception as e:
#                     print(f"Failed to fetch {url}: {e}")
#                     contents.append("ERROR")
#             else:
#                 contents.append("")  
#         else:
#             contents.append("")  
#     df['content'] = contents

#     df.to_csv(csv_file_path, index=False)
#     print(f"Updated CSV with 'content' column for previous month links.")

In [5]:
# fetch_and_append_content_from_csv("raw_data_source/KPMG_raw_scrapped_data.csv")

In [6]:

df = pd.read_excel('raw_data_source\PwC_raw_scrapped_data.xlsx')

In [7]:
df

,collection__item-link href,img-responsive src,ng-binding,ng-binding 2,paragraph,pdf_content
0,https://www.pwc.in/ghost-templates/sustainable...,https://www.pwc.in/content/dam/pwc/in/en/asset...,2025-07-04 00:00:00,Sustainable packaging in the FMCG and retail s...,This white paper provides an overview of the I...,April 2025Sustainable packaging \nin the FMCG ...
1,https://www.pwc.in/ghost-templates/electronics...,https://www.pwc.in/content/dam/pwc/in/en/asset...,2025-03-04 00:00:00,Electronics Component Manufacturing Scheme,The scheme seeks to attract substantial invest...,Electronics Component \nManufacturing Scheme T...
2,https://www.pwc.in/ghost-templates/agentic-ai-...,https://www.pwc.in/content/dam/pwc/in/en/asset...,27/03/25,Agentic AI in the human capital management (HC...,Leverage Oracle’s agentic AI technology to str...,Agentic AI in the human capital management (HC...
3,https://www.pwc.in/ghost-templates/indian-fami...,https://www.pwc.in/content/dam/pwc/in/en/asset...,26/03/25,Indian family offices – the new investors for ...,The relationship between family offices and st...,Indian family offices – \nthe new investors fo...
4,https://www.pwc.in/ghost-templates/intergenera...,https://www.pwc.in/content/dam/pwc/in/en/asset...,2025-11-03 00:00:00,Intergenerational trust: The key to succession...,Why building trust is necessary for family bus...,Intergenerational trust: \nThe key to success...
5,https://www.pwc.in/ghost-templates/understandi...,https://www.pwc.in/content/dam/pwc/in/en/asset...,2025-10-03 00:00:00,Understanding the impact of GenAI on the India...,Opportunities GenAI presents and the challenge...,NaN
6,https://www.pwc.in/ghost-templates/quality-mea...,https://www.pwc.in/content/dam/pwc/in/en/asset...,2025-07-03 00:00:00,Quality measures and standards for transitioni...,A roadmap to facilitate the transition to VBHC.,NaN
7,https://www.pwc.in/ghost-templates/the-mutual-...,https://www.pwc.in/content/dam/pwc/in/en/asset...,2025-05-03 00:00:00,The mutual funds route to Viksit Bharat @2047,A comprehensive roadmap for the evolution of t...,NaN
8,https://www.pwc.in/ghost-templates/financial-h...,https://www.pwc.in/content/dam/pwc/in/en/asset...,2025-04-03 00:00:00,Financial health: Transcending from access to ...,Explore India’s financial inclusion journey an...,TM\nMarch 2025Financial health: \nTranscendin...
9,https://www.pwc.in/ghost-templates/towards-a-c...,https://www.pwc.in/content/dam/pwc/in/en/asset...,2025-04-03 00:00:00,Towards a climate-resilient future: Strategies...,Explore the comprehensive climate-resilient ac...,NaN
10,https://www.pwc.in/ghost-templates/retail-rein...,https://www.pwc.in/content/dam/pwc/th/en/home/...,27/02/25,The retail reinvention paradigm,How brands could up their game,NaN
11,https://www.pwc.in/ghost-templates/pwc-indias-...,https://www.pwc.in/content/dam/pwc/gx/en/brand...,25/02/25,PwC India's Financial Services (FS) Risk Sympo...,The forum shed light on the evolving complexit...,May 2024\n6th February 2025Key takeaways from ...
12,https://www.pwc.in/ghost-templates/india-spend...,https://www.pwc.in/content/dam/pwc/gx/en/brand...,24/02/25,How India spends: A deep dive into consumer sp...,Powered by the robust growth of the Indian eco...,NaN
13,https://www.pwc.in/ghost-templates/future-qual...,https://www.pwc.in/content/dam/pwc/12/ja/servi...,21/02/25,The future of quality in manufacturing,"Explore the evolution of quality, the growing ...",The future of quality \nin manufacturing2 Pw...
14,https://www.pwc.in/ghost-templates/powering-au...,https://www.pwc.in/content/dam/pwc/in/en/asset...,18/02/25,Powering automation with agents,"Explore the world of APA, highlighting its app...",Powering automation \nwith agents\nPowering \...
15,https://www.pwc.in/ghost-templates/deals-at-a-...,https://www.pwc.in/content/dam/pwc/us/en/servi...,14/02/25,Deals at a glance: Annual review 2024,Read about the latest deals to uncover and exp...,1 | Deals at a glance: Annual review 2024\nD...
16,https://www.pwc.in/ghost-templates/digital-per...,https://www.pwc.in/content/dam/pwc/in/en/asset...,27/01/25,Digital Personal Data Protection Rules (2025),Key tenets of the DPDP rules,Digital Personal Data \nProtection Rules (2025...
17,https://www.pwc.in/ghost-templates/strengtheni...,https://www.pwc.in/content/dam/pwc/gx/en/brand...,22/01/25,Strengthening the impact of investments in rai...,Read about various interventions aimed at maxi...,Strengthening the impact \nof investments in r...
18,https://www.pwc.in/ghost-templates/28th-annual...,https://www.pwc.in/content/dam/pwc/gx/en/brand...,21/01/25,28th Annual Global CEO Survey: India perspective,Intelligent reinvention for tomorrow,[ERROR] EOF marker not found
19,https://www.pwc.in/publications/ceo-survey/28t...,https://www.pwc.in/content/dam/pwc/gx/en/ceo-s...,2025-10-01 00:00:00,28th Annual Global CEO Survey: India perspective,Dive into the Pwc's 28th Annual Global CEO Sur...,[ERROR] EOF marker not found
20,https://www.pwc.in/ghost-templates/enhancing-l...,https://www.pwc.in/content/dam/pwc/gx/en/brand...,24/12/24,Enhancing liquidity risk management frameworks...,It is imperative for banks to bridge gaps in l...,Enhancing liquidity risk \nmanagement framewor...
21,https://www.pwc.in/ghost-templates/unified-len...,https://www.pwc.in/content/dam/pwc/gx/en/brand...,18/12/24,Unified Lending Interface,Changing the credit landscape in India,Unified Lending Interface (ULI)\nChanging the ...
22,https://www.pwc.in/ghost-templates/building-su...,https://www.pwc.in/content/dam/pwc/gx/en/brand...,13/12/24,Building sustainable chemical manufacturing in...,Explore a roadmap for sustainability in India’...,NaN
23,https://www.pwc.in/ghost-templates/empowering-...,https://www.pwc.in/content/dam/pwc/gx/en/brand...,2024-11-12 00:00:00,Empowering legacy: The crucial role of family ...,Family businesses are the backbone of the Indi...,November 2024The crucial role of family govern...

In [8]:
df

,collection__item-link href,img-responsive src,ng-binding,ng-binding 2,paragraph,pdf_content
0,https://www.pwc.in/ghost-templates/sustainable...,https://www.pwc.in/content/dam/pwc/in/en/asset...,2025-07-04 00:00:00,Sustainable packaging in the FMCG and retail s...,This white paper provides an overview of the I...,April 2025Sustainable packaging \nin the FMCG ...
1,https://www.pwc.in/ghost-templates/electronics...,https://www.pwc.in/content/dam/pwc/in/en/asset...,2025-03-04 00:00:00,Electronics Component Manufacturing Scheme,The scheme seeks to attract substantial invest...,Electronics Component \nManufacturing Scheme T...
2,https://www.pwc.in/ghost-templates/agentic-ai-...,https://www.pwc.in/content/dam/pwc/in/en/asset...,27/03/25,Agentic AI in the human capital management (HC...,Leverage Oracle’s agentic AI technology to str...,Agentic AI in the human capital management (HC...
3,https://www.pwc.in/ghost-templates/indian-fami...,https://www.pwc.in/content/dam/pwc/in/en/asset...,26/03/25,Indian family offices – the new investors for ...,The relationship between family offices and st...,Indian family offices – \nthe new investors fo...
4,https://www.pwc.in/ghost-templates/intergenera...,https://www.pwc.in/content/dam/pwc/in/en/asset...,2025-11-03 00:00:00,Intergenerational trust: The key to succession...,Why building trust is necessary for family bus...,Intergenerational trust: \nThe key to success...
5,https://www.pwc.in/ghost-templates/understandi...,https://www.pwc.in/content/dam/pwc/in/en/asset...,2025-10-03 00:00:00,Understanding the impact of GenAI on the India...,Opportunities GenAI presents and the challenge...,NaN
6,https://www.pwc.in/ghost-templates/quality-mea...,https://www.pwc.in/content/dam/pwc/in/en/asset...,2025-07-03 00:00:00,Quality measures and standards for transitioni...,A roadmap to facilitate the transition to VBHC.,NaN
7,https://www.pwc.in/ghost-templates/the-mutual-...,https://www.pwc.in/content/dam/pwc/in/en/asset...,2025-05-03 00:00:00,The mutual funds route to Viksit Bharat @2047,A comprehensive roadmap for the evolution of t...,NaN
8,https://www.pwc.in/ghost-templates/financial-h...,https://www.pwc.in/content/dam/pwc/in/en/asset...,2025-04-03 00:00:00,Financial health: Transcending from access to ...,Explore India’s financial inclusion journey an...,TM\nMarch 2025Financial health: \nTranscendin...
9,https://www.pwc.in/ghost-templates/towards-a-c...,https://www.pwc.in/content/dam/pwc/in/en/asset...,2025-04-03 00:00:00,Towards a climate-resilient future: Strategies...,Explore the comprehensive climate-resilient ac...,NaN
10,https://www.pwc.in/ghost-templates/retail-rein...,https://www.pwc.in/content/dam/pwc/th/en/home/...,27/02/25,The retail reinvention paradigm,How brands could up their game,NaN
11,https://www.pwc.in/ghost-templates/pwc-indias-...,https://www.pwc.in/content/dam/pwc/gx/en/brand...,25/02/25,PwC India's Financial Services (FS) Risk Sympo...,The forum shed light on the evolving complexit...,May 2024\n6th February 2025Key takeaways from ...
12,https://www.pwc.in/ghost-templates/india-spend...,https://www.pwc.in/content/dam/pwc/gx/en/brand...,24/02/25,How India spends: A deep dive into consumer sp...,Powered by the robust growth of the Indian eco...,NaN
13,https://www.pwc.in/ghost-templates/future-qual...,https://www.pwc.in/content/dam/pwc/12/ja/servi...,21/02/25,The future of quality in manufacturing,"Explore the evolution of quality, the growing ...",The future of quality \nin manufacturing2 Pw...
14,https://www.pwc.in/ghost-templates/powering-au...,https://www.pwc.in/content/dam/pwc/in/en/asset...,18/02/25,Powering automation with agents,"Explore the world of APA, highlighting its app...",Powering automation \nwith agents\nPowering \...
15,https://www.pwc.in/ghost-templates/deals-at-a-...,https://www.pwc.in/content/dam/pwc/us/en/servi...,14/02/25,Deals at a glance: Annual review 2024,Read about the latest deals to uncover and exp...,1 | Deals at a glance: Annual review 2024\nD...
16,https://www.pwc.in/ghost-templates/digital-per...,https://www.pwc.in/content/dam/pwc/in/en/asset...,27/01/25,Digital Personal Data Protection Rules (2025),Key tenets of the DPDP rules,Digital Personal Data \nProtection Rules (2025...
17,https://www.pwc.in/ghost-templates/strengtheni...,https://www.pwc.in/content/dam/pwc/gx/en/brand...,22/01/25,Strengthening the impact of investments in rai...,Read about various interventions aimed at maxi...,Strengthening the impact \nof investments in r...
18,https://www.pwc.in/ghost-templates/28th-annual...,https://www.pwc.in/content/dam/pwc/gx/en/brand...,21/01/25,28th Annual Global CEO Survey: India perspective,Intelligent reinvention for tomorrow,[ERROR] EOF marker not found
19,https://www.pwc.in/publications/ceo-survey/28t...,https://www.pwc.in/content/dam/pwc/gx/en/ceo-s...,2025-10-01 00:00:00,28th Annual Global CEO Survey: India perspective,Dive into the Pwc's 28th Annual Global CEO Sur...,[ERROR] EOF marker not found
20,https://www.pwc.in/ghost-templates/enhancing-l...,https://www.pwc.in/content/dam/pwc/gx/en/brand...,24/12/24,Enhancing liquidity risk management frameworks...,It is imperative for banks to bridge gaps in l...,Enhancing liquidity risk \nmanagement framewor...
21,https://www.pwc.in/ghost-templates/unified-len...,https://www.pwc.in/content/dam/pwc/gx/en/brand...,18/12/24,Unified Lending Interface,Changing the credit landscape in India,Unified Lending Interface (ULI)\nChanging the ...
22,https://www.pwc.in/ghost-templates/building-su...,https://www.pwc.in/content/dam/pwc/gx/en/brand...,13/12/24,Building sustainable chemical manufacturing in...,Explore a roadmap for sustainability in India’...,NaN
23,https://www.pwc.in/ghost-templates/empowering-...,https://www.pwc.in/content/dam/pwc/gx/en/brand...,2024-11-12 00:00:00,Empowering legacy: The crucial role of family ...,Family businesses are the backbone of the Indi...,November 2024The crucial role of family govern...

In [9]:
df['ng-binding']

0     2025-07-04 00:00:00
1     2025-03-04 00:00:00
2                27/03/25
3                26/03/25
4     2025-11-03 00:00:00
5     2025-10-03 00:00:00
6     2025-07-03 00:00:00
7     2025-05-03 00:00:00
8     2025-04-03 00:00:00
9     2025-04-03 00:00:00
10               27/02/25
11               25/02/25
12               24/02/25
13               21/02/25
14               18/02/25
15               14/02/25
16               27/01/25
17               22/01/25
18               21/01/25
19    2025-10-01 00:00:00
20               24/12/24
21               18/12/24
22               13/12/24
23    2024-11-12 00:00:00
Name: ng-binding, dtype: object

In [10]:
df['ng-binding'] = df['ng-binding'].astype(str)

In [11]:
# Helper function to detect and parse format
def parse_date(val):
    if re.match(r"\d{2}/\d{2}/\d{4}", val):  # dd/mm/yyyy
        return pd.to_datetime(val, dayfirst=True, errors='coerce')
    else:  # assume yyyy-mm-dd or yyyy-mm-dd hh:mm:ss
        return pd.to_datetime(val, dayfirst=True, errors='coerce')

In [12]:
# Applying parser
df['date'] = df['ng-binding'].apply(parse_date)

In [13]:
df['date']

0    2025-04-07
1    2025-04-03
2    2025-03-27
3    2025-03-26
4    2025-03-11
5    2025-03-10
6    2025-03-07
7    2025-03-05
8    2025-03-04
9    2025-03-04
10   2025-02-27
11   2025-02-25
12   2025-02-24
13   2025-02-21
14   2025-02-18
15   2025-02-14
16   2025-01-27
17   2025-01-22
18   2025-01-21
19   2025-01-10
20   2024-12-24
21   2024-12-18
22   2024-12-13
23   2024-12-11
Name: date, dtype: datetime64[ns]

In [14]:
df['date'] = df['date'].dt.date

# Filter for March 2025
march_df = df[(df['date'] >= pd.to_datetime("2025-03-01").date()) &
              (df['date'] <= pd.to_datetime("2025-03-31").date())]

In [15]:
march_df

,collection__item-link href,img-responsive src,ng-binding,ng-binding 2,paragraph,pdf_content,date
2,https://www.pwc.in/ghost-templates/agentic-ai-...,https://www.pwc.in/content/dam/pwc/in/en/asset...,27/03/25,Agentic AI in the human capital management (HC...,Leverage Oracle’s agentic AI technology to str...,Agentic AI in the human capital management (HC...,2025-03-27
3,https://www.pwc.in/ghost-templates/indian-fami...,https://www.pwc.in/content/dam/pwc/in/en/asset...,26/03/25,Indian family offices – the new investors for ...,The relationship between family offices and st...,Indian family offices – \nthe new investors fo...,2025-03-26
4,https://www.pwc.in/ghost-templates/intergenera...,https://www.pwc.in/content/dam/pwc/in/en/asset...,2025-11-03 00:00:00,Intergenerational trust: The key to succession...,Why building trust is necessary for family bus...,Intergenerational trust: \nThe key to success...,2025-03-11
5,https://www.pwc.in/ghost-templates/understandi...,https://www.pwc.in/content/dam/pwc/in/en/asset...,2025-10-03 00:00:00,Understanding the impact of GenAI on the India...,Opportunities GenAI presents and the challenge...,NaN,2025-03-10
6,https://www.pwc.in/ghost-templates/quality-mea...,https://www.pwc.in/content/dam/pwc/in/en/asset...,2025-07-03 00:00:00,Quality measures and standards for transitioni...,A roadmap to facilitate the transition to VBHC.,NaN,2025-03-07
7,https://www.pwc.in/ghost-templates/the-mutual-...,https://www.pwc.in/content/dam/pwc/in/en/asset...,2025-05-03 00:00:00,The mutual funds route to Viksit Bharat @2047,A comprehensive roadmap for the evolution of t...,NaN,2025-03-05
8,https://www.pwc.in/ghost-templates/financial-h...,https://www.pwc.in/content/dam/pwc/in/en/asset...,2025-04-03 00:00:00,Financial health: Transcending from access to ...,Explore India’s financial inclusion journey an...,TM\nMarch 2025Financial health: \nTranscendin...,2025-03-04
9,https://www.pwc.in/ghost-templates/towards-a-c...,https://www.pwc.in/content/dam/pwc/in/en/asset...,2025-04-03 00:00:00,Towards a climate-resilient future: Strategies...,Explore the comprehensive climate-resilient ac...,NaN,2025-03-04

In [16]:
march_df.drop('ng-binding',inplace=True,axis=1)

C:\Users\Admin\AppData\Local\Temp\ipykernel_17436\545348834.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  march_df.drop('ng-binding',inplace=True,axis=1)

In [17]:
march_df

,collection__item-link href,img-responsive src,ng-binding 2,paragraph,pdf_content,date
2,https://www.pwc.in/ghost-templates/agentic-ai-...,https://www.pwc.in/content/dam/pwc/in/en/asset...,Agentic AI in the human capital management (HC...,Leverage Oracle’s agentic AI technology to str...,Agentic AI in the human capital management (HC...,2025-03-27
3,https://www.pwc.in/ghost-templates/indian-fami...,https://www.pwc.in/content/dam/pwc/in/en/asset...,Indian family offices – the new investors for ...,The relationship between family offices and st...,Indian family offices – \nthe new investors fo...,2025-03-26
4,https://www.pwc.in/ghost-templates/intergenera...,https://www.pwc.in/content/dam/pwc/in/en/asset...,Intergenerational trust: The key to succession...,Why building trust is necessary for family bus...,Intergenerational trust: \nThe key to success...,2025-03-11
5,https://www.pwc.in/ghost-templates/understandi...,https://www.pwc.in/content/dam/pwc/in/en/asset...,Understanding the impact of GenAI on the India...,Opportunities GenAI presents and the challenge...,NaN,2025-03-10
6,https://www.pwc.in/ghost-templates/quality-mea...,https://www.pwc.in/content/dam/pwc/in/en/asset...,Quality measures and standards for transitioni...,A roadmap to facilitate the transition to VBHC.,NaN,2025-03-07
7,https://www.pwc.in/ghost-templates/the-mutual-...,https://www.pwc.in/content/dam/pwc/in/en/asset...,The mutual funds route to Viksit Bharat @2047,A comprehensive roadmap for the evolution of t...,NaN,2025-03-05
8,https://www.pwc.in/ghost-templates/financial-h...,https://www.pwc.in/content/dam/pwc/in/en/asset...,Financial health: Transcending from access to ...,Explore India’s financial inclusion journey an...,TM\nMarch 2025Financial health: \nTranscendin...,2025-03-04
9,https://www.pwc.in/ghost-templates/towards-a-c...,https://www.pwc.in/content/dam/pwc/in/en/asset...,Towards a climate-resilient future: Strategies...,Explore the comprehensive climate-resilient ac...,NaN,2025-03-04

In [18]:
march_df.drop('img-responsive src',inplace=True,axis=1)

C:\Users\Admin\AppData\Local\Temp\ipykernel_17436\3800299121.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  march_df.drop('img-responsive src',inplace=True,axis=1)

In [19]:
march_df['collection__item-link href']

2    https://www.pwc.in/ghost-templates/agentic-ai-...
3    https://www.pwc.in/ghost-templates/indian-fami...
4    https://www.pwc.in/ghost-templates/intergenera...
5    https://www.pwc.in/ghost-templates/understandi...
6    https://www.pwc.in/ghost-templates/quality-mea...
7    https://www.pwc.in/ghost-templates/the-mutual-...
8    https://www.pwc.in/ghost-templates/financial-h...
9    https://www.pwc.in/ghost-templates/towards-a-c...
Name: collection__item-link href, dtype: object

In [20]:

def extract_pdf_text(url):
    try:
        response = requests.get(url, timeout=10)
        if response.status_code == 200:
            pdf_file = BytesIO(response.content)
            doc = fitz.open(stream=pdf_file, filetype="pdf")
            text = ""
            for page in doc:
                text += page.get_text()
            return text.strip()
        else:
            return f"Failed: HTTP {response.status_code}"
    except Exception as e:
        return f"Error: {str(e)}"

In [21]:
mask = march_df["pdf_content"].isna() | (march_df["pdf_content"].str.strip() == "")

In [22]:
for idx in march_df[mask].index:
    link = march_df.at[idx, "collection__item-link href"]  # replace with your actual column name
    content = extract_pdf_text(link)
    march_df.at[idx, "pdf_content"] = content

In [23]:
march_df.to_excel("march_df_updated.xlsx", index=False)

## KPMG data

In [27]:
import pandas as pd

# Load the CSV file
df = pd.read_csv("raw_data_source\KPMG_raw_scrapped_data.csv")  # Replace with your actual file name

# Save it as an Excel file
df.to_excel("KPMG_raw_data.xlsx", index=False)

In [28]:
kpmg_data = pd.read_excel('KPMG_raw_data.xlsx')

In [29]:
kpmg_data

,web-scraper-order,web-scraper-start-url,blogs,blogs-href,nextpage,content
0,1744287928-1,https://kpmg.com/in/en/insights.html,India CX Report'25: Commercial Real Estate\n ...,https://kpmg.com/in/en/insights/2025/03/india-...,NaN,India CX Report'25: Commercial Real Estate clo...
1,1744287928-2,https://kpmg.com/in/en/insights.html,India CX Report'25: Residential Real Estate\n ...,https://kpmg.com/in/en/insights/2025/03/india-...,NaN,India CX Report'25: Residential Real Estate cl...
2,1744287928-3,https://kpmg.com/in/en/insights.html,India CX Report'25: Real Estate\n \n ...,https://kpmg.com/in/en/insights/2025/03/india-...,NaN,India CX Report'25: Real Estate close contact_...
3,1744287928-4,https://kpmg.com/in/en/insights.html,You can with AI\n \n Discover en...,https://kpmg.com/in/en/insights/2025/04/you-ca...,NaN,NaN
4,1744287928-5,https://kpmg.com/in/en/insights.html,Powering the Future: How AI is Driving the Nex...,https://kpmg.com/in/en/blogs/2025/04/powering-...,NaN,NaN
...,...,...,...,...,...,...
441,1744287928-442,https://kpmg.com/in/en/insights.html,India’s debut sovereign green bond framework: ...,https://kpmg.com/in/en/insights/2022/12/india-...,NaN,NaN
442,1744287928-443,https://kpmg.com/in/en/insights.html,KPMG 2022 CEO Outlook\n \n Growt...,https://kpmg.com/in/en/insights/2022/10/kpmg-2...,NaN,NaN
443,1744287928-444,https://kpmg.com/in/en/insights.html,Mastering intentional experiences - India CX r...,https://kpmg.com/in/en/insights/2023/08/master...,NaN,NaN
444,1744287928-445,https://kpmg.com/in/en/insights.html,First Notes - Archive\n \n First...,https://kpmg.com/in/en/insights/2021/04/first-...,NaN,NaN
445,1744287928-446,https://kpmg.com/in/en/insights.html,Accounting and Auditing Update - Archive\n ...,https://kpmg.com/in/en/insights/2021/04/aau-ar...,NaN,NaN

In [30]:
kpmg_data["blogs-href"] = kpmg_data["blogs-href"].astype(str)

In [31]:
march_2025_df_kpmg = df[df["blogs-href"].str.contains(r"/2025/03/")].copy()

In [32]:
march_2025_df_kpmg.reset_index(drop=True, inplace=True)

In [33]:
march_2025_df_kpmg

,web-scraper-order,web-scraper-start-url,blogs,blogs-href,nextpage,content
0,1744287928-1,https://kpmg.com/in/en/insights.html,India CX Report'25: Commercial Real Estate\n ...,https://kpmg.com/in/en/insights/2025/03/india-...,NaN,India CX Report'25: Commercial Real Estate clo...
1,1744287928-2,https://kpmg.com/in/en/insights.html,India CX Report'25: Residential Real Estate\n ...,https://kpmg.com/in/en/insights/2025/03/india-...,NaN,India CX Report'25: Residential Real Estate cl...
2,1744287928-3,https://kpmg.com/in/en/insights.html,India CX Report'25: Real Estate\n \n ...,https://kpmg.com/in/en/insights/2025/03/india-...,NaN,India CX Report'25: Real Estate close contact_...
3,1744287928-6,https://kpmg.com/in/en/insights.html,India CX Report'25: Premium Hotels\n \n...,https://kpmg.com/in/en/insights/2025/03/india-...,NaN,India CX Report'25: Premium Hotels close conta...
4,1744287928-7,https://kpmg.com/in/en/insights.html,India CX Report'25: Hotels\n \n ...,https://kpmg.com/in/en/insights/2025/03/india-...,NaN,India CX Report'25: Hotels close contact_mail ...
5,1744287928-8,https://kpmg.com/in/en/insights.html,India CX Report'25: Budget Hotels\n \n ...,https://kpmg.com/in/en/insights/2025/03/india-...,NaN,India CX Report'25: Budget Hotels close contac...
6,1744287928-10,https://kpmg.com/in/en/insights.html,India CX Report'25: Consumer Durables\n ...,https://kpmg.com/in/en/insights/2025/03/india-...,NaN,India CX Report'25: Consumer Durables close co...
7,1744287928-11,https://kpmg.com/in/en/insights.html,India CX Report'25: Small Appliances\n ...,https://kpmg.com/in/en/insights/2025/03/india-...,NaN,India CX Report'25: Small Appliances close con...
8,1744287928-12,https://kpmg.com/in/en/insights.html,India CX Report'25: Large Appliances\n ...,https://kpmg.com/in/en/insights/2025/03/india-...,NaN,India CX Report'25: Large Appliances close con...
9,1744287928-17,https://kpmg.com/in/en/insights.html,Evolving third party landscape in India's medi...,https://kpmg.com/in/en/insights/2025/03/evolvi...,NaN,Evolving third party landscape in India's medi...
10,1744287928-18,https://kpmg.com/in/en/insights.html,Issue no. 104 | March 2025\n \n ...,https://kpmg.com/in/en/insights/2025/03/aau-ac...,NaN,Issue no. 104 | March 2025 close contact_mail ...
11,1744287928-19,https://kpmg.com/in/en/insights.html,Related party transactions – Minimum informati...,https://kpmg.com/in/en/insights/2025/03/firstn...,NaN,Related party transactions – Minimum informati...
12,1744287928-20,https://kpmg.com/in/en/insights.html,Third-party risks in the pharmaceutical supply...,https://kpmg.com/in/en/insights/2025/03/third-...,NaN,Third-party risks in the pharmaceutical supply...
13,1744287928-23,https://kpmg.com/in/en/insights.html,Intelligent retail\n \n Explorin...,https://kpmg.com/in/en/insights/2025/03/intell...,NaN,Intelligent retail close contact_mail Contact ...
14,1744287928-25,https://kpmg.com/in/en/insights.html,India’s digital transformation provides a blue...,https://kpmg.com/in/en/blogs/2025/03/indias-di...,NaN,India’s digital transformation provides a blue...
15,1744287928-26,https://kpmg.com/in/en/insights.html,Cybersecurity considerations 2025\n \n ...,https://kpmg.com/in/en/insights/2025/03/cybers...,NaN,Cybersecurity considerations 2025 close contac...
16,1744287928-27,https://kpmg.com/in/en/insights.html,India CX Report'25: Airlines\n \n ...,https://kpmg.com/in/en/insights/2025/03/india-...,NaN,India CX Report'25: Airlines close contact_mai...
17,1744287928-28,https://kpmg.com/in/en/insights.html,Mastering intentional experiences: India CX re...,https://kpmg.com/in/en/insights/2025/03/india-...,NaN,Mastering intentional experiences: India CX re...
18,1744287928-29,https://kpmg.com/in/en/insights.html,Navigating Reserve Bank of India’s guidelines ...,https://kpmg.com/in/en/insights/2025/03/naviga...,NaN,Navigating Reserve Bank of India’s guidelines ...
19,1744287928-30,https://kpmg.com/in/en/insights.html,"Indian ports are now better, but what’s next?\...",https://kpmg.com/in/en/blogs/2025/03/indian-po...,NaN,"Indian ports are now better, but what’s next? ..."
20,1744287928-31,https://kpmg.com/in/en/insights.html,Innovative strategies for cost optimisation – ...,https://kpmg.com/in/en/blogs/2025/03/innovativ...,NaN,Innovative strategies for cost optimisation – ...
21,1744287928-32,https://kpmg.com/in/en/insights.html,Aviation\n \n Airlines need to m...,https://kpmg.com/in/en/insights/2025/03/india-...,NaN,India CX Report'25: Airlines close contact_mai...
22,1744287928-33,https://kpmg.com/in/en/insights.html,Pulse of Fintech: H2 2024\n \n B...,https://kpmg.com/in/en/insights/2025/03/pulse-...,NaN,Pulse of Fintech: H2 2024 close contact_mail C...
23,1744287928-34,https://kpmg.com/in/en/insights.html,The rise of silver generation: Transforming th...,https://kpmg.com/in/en/insights/2025/03/the-ri...,NaN,The rise of silver generation: Transforming th...
24,1744287928-35,https://kpmg.com/in/en/insights.html,Aviation leasing and financing ecosystem at GI...,https://kpmg.com/in/en/insights/2025/03/aviati...,NaN,Aviation leasing and financing ecosystem at GI...
25,1744287928-36,https://kpmg.com/in/en/insights.html,Textile industry embraces sustainability and i...,https://kpmg.com/in/en/blogs/2025/03/textile-i...,NaN,Textile industry embraces sustainability and i...

In [36]:
march_df

,collection__item-link href,ng-binding 2,paragraph,pdf_content,date
2,https://www.pwc.in/ghost-templates/agentic-ai-...,Agentic AI in the human capital management (HC...,Leverage Oracle’s agentic AI technology to str...,Agentic AI in the human capital management (HC...,2025-03-27
3,https://www.pwc.in/ghost-templates/indian-fami...,Indian family offices – the new investors for ...,The relationship between family offices and st...,Indian family offices – \nthe new investors fo...,2025-03-26
4,https://www.pwc.in/ghost-templates/intergenera...,Intergenerational trust: The key to succession...,Why building trust is necessary for family bus...,Intergenerational trust: \nThe key to success...,2025-03-11
5,https://www.pwc.in/ghost-templates/understandi...,Understanding the impact of GenAI on the India...,Opportunities GenAI presents and the challenge...,March 2024\nIndian healthcare ecosystem \nUnde...,2025-03-10
6,https://www.pwc.in/ghost-templates/quality-mea...,Quality measures and standards for transitioni...,A roadmap to facilitate the transition to VBHC.,Quality measures and standards \nMarch 2025\nf...,2025-03-07
7,https://www.pwc.in/ghost-templates/the-mutual-...,The mutual funds route to Viksit Bharat @2047,A comprehensive roadmap for the evolution of t...,The mutual funds route \nto Viksit Bharat @204...,2025-03-05
8,https://www.pwc.in/ghost-templates/financial-h...,Financial health: Transcending from access to ...,Explore India’s financial inclusion journey an...,TM\nMarch 2025Financial health: \nTranscendin...,2025-03-04
9,https://www.pwc.in/ghost-templates/towards-a-c...,Towards a climate-resilient future: Strategies...,Explore the comprehensive climate-resilient ac...,Towards a climate-resilient \nfuture: Strategi...,2025-03-04

In [37]:
march_2025_df_kpmg.columns

Index(['web-scraper-order', 'web-scraper-start-url', 'blogs', 'blogs-href',
       'nextpage', 'content'],
      dtype='object')

In [42]:
columns = ['blogs','blogs-href','content']
dff = march_2025_df_kpmg[columns]

In [44]:
dff['source'] = 'KPMG'

C:\Users\Admin\AppData\Local\Temp\ipykernel_17436\3606595929.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dff['source'] = 'KPMG'

In [45]:
dff

,blogs,blogs-href,content,source
0,India CX Report'25: Commercial Real Estate\n ...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Commercial Real Estate clo...,KPMG
1,India CX Report'25: Residential Real Estate\n ...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Residential Real Estate cl...,KPMG
2,India CX Report'25: Real Estate\n \n ...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Real Estate close contact_...,KPMG
3,India CX Report'25: Premium Hotels\n \n...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Premium Hotels close conta...,KPMG
4,India CX Report'25: Hotels\n \n ...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Hotels close contact_mail ...,KPMG
5,India CX Report'25: Budget Hotels\n \n ...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Budget Hotels close contac...,KPMG
6,India CX Report'25: Consumer Durables\n ...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Consumer Durables close co...,KPMG
7,India CX Report'25: Small Appliances\n ...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Small Appliances close con...,KPMG
8,India CX Report'25: Large Appliances\n ...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Large Appliances close con...,KPMG
9,Evolving third party landscape in India's medi...,https://kpmg.com/in/en/insights/2025/03/evolvi...,Evolving third party landscape in India's medi...,KPMG
10,Issue no. 104 | March 2025\n \n ...,https://kpmg.com/in/en/insights/2025/03/aau-ac...,Issue no. 104 | March 2025 close contact_mail ...,KPMG
11,Related party transactions – Minimum informati...,https://kpmg.com/in/en/insights/2025/03/firstn...,Related party transactions – Minimum informati...,KPMG
12,Third-party risks in the pharmaceutical supply...,https://kpmg.com/in/en/insights/2025/03/third-...,Third-party risks in the pharmaceutical supply...,KPMG
13,Intelligent retail\n \n Explorin...,https://kpmg.com/in/en/insights/2025/03/intell...,Intelligent retail close contact_mail Contact ...,KPMG
14,India’s digital transformation provides a blue...,https://kpmg.com/in/en/blogs/2025/03/indias-di...,India’s digital transformation provides a blue...,KPMG
15,Cybersecurity considerations 2025\n \n ...,https://kpmg.com/in/en/insights/2025/03/cybers...,Cybersecurity considerations 2025 close contac...,KPMG
16,India CX Report'25: Airlines\n \n ...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Airlines close contact_mai...,KPMG
17,Mastering intentional experiences: India CX re...,https://kpmg.com/in/en/insights/2025/03/india-...,Mastering intentional experiences: India CX re...,KPMG
18,Navigating Reserve Bank of India’s guidelines ...,https://kpmg.com/in/en/insights/2025/03/naviga...,Navigating Reserve Bank of India’s guidelines ...,KPMG
19,"Indian ports are now better, but what’s next?\...",https://kpmg.com/in/en/blogs/2025/03/indian-po...,"Indian ports are now better, but what’s next? ...",KPMG
20,Innovative strategies for cost optimisation – ...,https://kpmg.com/in/en/blogs/2025/03/innovativ...,Innovative strategies for cost optimisation – ...,KPMG
21,Aviation\n \n Airlines need to m...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Airlines close contact_mai...,KPMG
22,Pulse of Fintech: H2 2024\n \n B...,https://kpmg.com/in/en/insights/2025/03/pulse-...,Pulse of Fintech: H2 2024 close contact_mail C...,KPMG
23,The rise of silver generation: Transforming th...,https://kpmg.com/in/en/insights/2025/03/the-ri...,The rise of silver generation: Transforming th...,KPMG
24,Aviation leasing and financing ecosystem at GI...,https://kpmg.com/in/en/insights/2025/03/aviati...,Aviation leasing and financing ecosystem at GI...,KPMG
25,Textile industry embraces sustainability and i...,https://kpmg.com/in/en/blogs/2025/03/textile-i...,Textile industry embraces sustainability and i...,KPMG

In [49]:
def extract_date_from_url(url):
    match = re.search(r'/(\d{4})/(\d{2})/', url)
    if match:
        year, month = match.groups()
        return f"{year}-{month}-01"  # optional: add day=01 to make it a valid date
    return None

In [50]:
# Apply function to create new date column
dff['date'] = dff['blogs-href'].apply(extract_date_from_url)

C:\Users\Admin\AppData\Local\Temp\ipykernel_17436\2811179927.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dff['date'] = dff['blogs-href'].apply(extract_date_from_url)

In [51]:
dff['date'] = pd.to_datetime(dff['date'])

C:\Users\Admin\AppData\Local\Temp\ipykernel_17436\3661434889.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dff['date'] = pd.to_datetime(dff['date'])

#### In KPMG data exact date is not provided So I have taken 01-03-2025 as date for all the articles for simplicity.

In [52]:
dff

,blogs,blogs-href,content,source,date
0,India CX Report'25: Commercial Real Estate\n ...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Commercial Real Estate clo...,KPMG,2025-03-01
1,India CX Report'25: Residential Real Estate\n ...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Residential Real Estate cl...,KPMG,2025-03-01
2,India CX Report'25: Real Estate\n \n ...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Real Estate close contact_...,KPMG,2025-03-01
3,India CX Report'25: Premium Hotels\n \n...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Premium Hotels close conta...,KPMG,2025-03-01
4,India CX Report'25: Hotels\n \n ...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Hotels close contact_mail ...,KPMG,2025-03-01
5,India CX Report'25: Budget Hotels\n \n ...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Budget Hotels close contac...,KPMG,2025-03-01
6,India CX Report'25: Consumer Durables\n ...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Consumer Durables close co...,KPMG,2025-03-01
7,India CX Report'25: Small Appliances\n ...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Small Appliances close con...,KPMG,2025-03-01
8,India CX Report'25: Large Appliances\n ...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Large Appliances close con...,KPMG,2025-03-01
9,Evolving third party landscape in India's medi...,https://kpmg.com/in/en/insights/2025/03/evolvi...,Evolving third party landscape in India's medi...,KPMG,2025-03-01
10,Issue no. 104 | March 2025\n \n ...,https://kpmg.com/in/en/insights/2025/03/aau-ac...,Issue no. 104 | March 2025 close contact_mail ...,KPMG,2025-03-01
11,Related party transactions – Minimum informati...,https://kpmg.com/in/en/insights/2025/03/firstn...,Related party transactions – Minimum informati...,KPMG,2025-03-01
12,Third-party risks in the pharmaceutical supply...,https://kpmg.com/in/en/insights/2025/03/third-...,Third-party risks in the pharmaceutical supply...,KPMG,2025-03-01
13,Intelligent retail\n \n Explorin...,https://kpmg.com/in/en/insights/2025/03/intell...,Intelligent retail close contact_mail Contact ...,KPMG,2025-03-01
14,India’s digital transformation provides a blue...,https://kpmg.com/in/en/blogs/2025/03/indias-di...,India’s digital transformation provides a blue...,KPMG,2025-03-01
15,Cybersecurity considerations 2025\n \n ...,https://kpmg.com/in/en/insights/2025/03/cybers...,Cybersecurity considerations 2025 close contac...,KPMG,2025-03-01
16,India CX Report'25: Airlines\n \n ...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Airlines close contact_mai...,KPMG,2025-03-01
17,Mastering intentional experiences: India CX re...,https://kpmg.com/in/en/insights/2025/03/india-...,Mastering intentional experiences: India CX re...,KPMG,2025-03-01
18,Navigating Reserve Bank of India’s guidelines ...,https://kpmg.com/in/en/insights/2025/03/naviga...,Navigating Reserve Bank of India’s guidelines ...,KPMG,2025-03-01
19,"Indian ports are now better, but what’s next?\...",https://kpmg.com/in/en/blogs/2025/03/indian-po...,"Indian ports are now better, but what’s next? ...",KPMG,2025-03-01
20,Innovative strategies for cost optimisation – ...,https://kpmg.com/in/en/blogs/2025/03/innovativ...,Innovative strategies for cost optimisation – ...,KPMG,2025-03-01
21,Aviation\n \n Airlines need to m...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Airlines close contact_mai...,KPMG,2025-03-01
22,Pulse of Fintech: H2 2024\n \n B...,https://kpmg.com/in/en/insights/2025/03/pulse-...,Pulse of Fintech: H2 2024 close contact_mail C...,KPMG,2025-03-01
23,The rise of silver generation: Transforming th...,https://kpmg.com/in/en/insights/2025/03/the-ri...,The rise of silver generation: Transforming th...,KPMG,2025-03-01
24,Aviation leasing and financing ecosystem at GI...,https://kpmg.com/in/en/insights/2025/03/aviati...,Aviation leasing and financing ecosystem at GI...,KPMG,2025-03-01
25,Textile industry embraces sustainability and i...,https://kpmg.com/in/en/blogs/2025/03/textile-i...,Textile industry embraces sustainability and i...,KPMG,2025-03-01

In [58]:
march_df.columns

Index(['collection__item-link href', 'ng-binding 2', 'paragraph',
       'pdf_content', 'date'],
      dtype='object')

In [63]:
columns = ['ng-binding 2','collection__item-link href','pdf_content','date']
dff2 = march_df[columns]

In [65]:
dff2['source'] = 'PWC'

In [66]:
dff2

,ng-binding 2,collection__item-link href,pdf_content,date,source
2,Agentic AI in the human capital management (HC...,https://www.pwc.in/ghost-templates/agentic-ai-...,Agentic AI in the human capital management (HC...,2025-03-27,PWC
3,Indian family offices – the new investors for ...,https://www.pwc.in/ghost-templates/indian-fami...,Indian family offices – \nthe new investors fo...,2025-03-26,PWC
4,Intergenerational trust: The key to succession...,https://www.pwc.in/ghost-templates/intergenera...,Intergenerational trust: \nThe key to success...,2025-03-11,PWC
5,Understanding the impact of GenAI on the India...,https://www.pwc.in/ghost-templates/understandi...,March 2024\nIndian healthcare ecosystem \nUnde...,2025-03-10,PWC
6,Quality measures and standards for transitioni...,https://www.pwc.in/ghost-templates/quality-mea...,Quality measures and standards \nMarch 2025\nf...,2025-03-07,PWC
7,The mutual funds route to Viksit Bharat @2047,https://www.pwc.in/ghost-templates/the-mutual-...,The mutual funds route \nto Viksit Bharat @204...,2025-03-05,PWC
8,Financial health: Transcending from access to ...,https://www.pwc.in/ghost-templates/financial-h...,TM\nMarch 2025Financial health: \nTranscendin...,2025-03-04,PWC
9,Towards a climate-resilient future: Strategies...,https://www.pwc.in/ghost-templates/towards-a-c...,Towards a climate-resilient \nfuture: Strategi...,2025-03-04,PWC

In [67]:
dff2.columns = ['title','link','content','date','source']

In [68]:
dff2

,title,link,content,date,source
2,Agentic AI in the human capital management (HC...,https://www.pwc.in/ghost-templates/agentic-ai-...,Agentic AI in the human capital management (HC...,2025-03-27,PWC
3,Indian family offices – the new investors for ...,https://www.pwc.in/ghost-templates/indian-fami...,Indian family offices – \nthe new investors fo...,2025-03-26,PWC
4,Intergenerational trust: The key to succession...,https://www.pwc.in/ghost-templates/intergenera...,Intergenerational trust: \nThe key to success...,2025-03-11,PWC
5,Understanding the impact of GenAI on the India...,https://www.pwc.in/ghost-templates/understandi...,March 2024\nIndian healthcare ecosystem \nUnde...,2025-03-10,PWC
6,Quality measures and standards for transitioni...,https://www.pwc.in/ghost-templates/quality-mea...,Quality measures and standards \nMarch 2025\nf...,2025-03-07,PWC
7,The mutual funds route to Viksit Bharat @2047,https://www.pwc.in/ghost-templates/the-mutual-...,The mutual funds route \nto Viksit Bharat @204...,2025-03-05,PWC
8,Financial health: Transcending from access to ...,https://www.pwc.in/ghost-templates/financial-h...,TM\nMarch 2025Financial health: \nTranscendin...,2025-03-04,PWC
9,Towards a climate-resilient future: Strategies...,https://www.pwc.in/ghost-templates/towards-a-c...,Towards a climate-resilient \nfuture: Strategi...,2025-03-04,PWC

In [69]:
dff

,blogs,blogs-href,content,source,date
0,India CX Report'25: Commercial Real Estate\n ...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Commercial Real Estate clo...,KPMG,2025-03-01
1,India CX Report'25: Residential Real Estate\n ...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Residential Real Estate cl...,KPMG,2025-03-01
2,India CX Report'25: Real Estate\n \n ...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Real Estate close contact_...,KPMG,2025-03-01
3,India CX Report'25: Premium Hotels\n \n...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Premium Hotels close conta...,KPMG,2025-03-01
4,India CX Report'25: Hotels\n \n ...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Hotels close contact_mail ...,KPMG,2025-03-01
5,India CX Report'25: Budget Hotels\n \n ...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Budget Hotels close contac...,KPMG,2025-03-01
6,India CX Report'25: Consumer Durables\n ...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Consumer Durables close co...,KPMG,2025-03-01
7,India CX Report'25: Small Appliances\n ...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Small Appliances close con...,KPMG,2025-03-01
8,India CX Report'25: Large Appliances\n ...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Large Appliances close con...,KPMG,2025-03-01
9,Evolving third party landscape in India's medi...,https://kpmg.com/in/en/insights/2025/03/evolvi...,Evolving third party landscape in India's medi...,KPMG,2025-03-01
10,Issue no. 104 | March 2025\n \n ...,https://kpmg.com/in/en/insights/2025/03/aau-ac...,Issue no. 104 | March 2025 close contact_mail ...,KPMG,2025-03-01
11,Related party transactions – Minimum informati...,https://kpmg.com/in/en/insights/2025/03/firstn...,Related party transactions – Minimum informati...,KPMG,2025-03-01
12,Third-party risks in the pharmaceutical supply...,https://kpmg.com/in/en/insights/2025/03/third-...,Third-party risks in the pharmaceutical supply...,KPMG,2025-03-01
13,Intelligent retail\n \n Explorin...,https://kpmg.com/in/en/insights/2025/03/intell...,Intelligent retail close contact_mail Contact ...,KPMG,2025-03-01
14,India’s digital transformation provides a blue...,https://kpmg.com/in/en/blogs/2025/03/indias-di...,India’s digital transformation provides a blue...,KPMG,2025-03-01
15,Cybersecurity considerations 2025\n \n ...,https://kpmg.com/in/en/insights/2025/03/cybers...,Cybersecurity considerations 2025 close contac...,KPMG,2025-03-01
16,India CX Report'25: Airlines\n \n ...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Airlines close contact_mai...,KPMG,2025-03-01
17,Mastering intentional experiences: India CX re...,https://kpmg.com/in/en/insights/2025/03/india-...,Mastering intentional experiences: India CX re...,KPMG,2025-03-01
18,Navigating Reserve Bank of India’s guidelines ...,https://kpmg.com/in/en/insights/2025/03/naviga...,Navigating Reserve Bank of India’s guidelines ...,KPMG,2025-03-01
19,"Indian ports are now better, but what’s next?\...",https://kpmg.com/in/en/blogs/2025/03/indian-po...,"Indian ports are now better, but what’s next? ...",KPMG,2025-03-01
20,Innovative strategies for cost optimisation – ...,https://kpmg.com/in/en/blogs/2025/03/innovativ...,Innovative strategies for cost optimisation – ...,KPMG,2025-03-01
21,Aviation\n \n Airlines need to m...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Airlines close contact_mai...,KPMG,2025-03-01
22,Pulse of Fintech: H2 2024\n \n B...,https://kpmg.com/in/en/insights/2025/03/pulse-...,Pulse of Fintech: H2 2024 close contact_mail C...,KPMG,2025-03-01
23,The rise of silver generation: Transforming th...,https://kpmg.com/in/en/insights/2025/03/the-ri...,The rise of silver generation: Transforming th...,KPMG,2025-03-01
24,Aviation leasing and financing ecosystem at GI...,https://kpmg.com/in/en/insights/2025/03/aviati...,Aviation leasing and financing ecosystem at GI...,KPMG,2025-03-01
25,Textile industry embraces sustainability and i...,https://kpmg.com/in/en/blogs/2025/03/textile-i...,Textile industry embraces sustainability and i...,KPMG,2025-03-01

In [72]:
dff.columns = ['title','link','content','source','date']

In [73]:
dff

,title,link,content,source,date
0,India CX Report'25: Commercial Real Estate\n ...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Commercial Real Estate clo...,KPMG,2025-03-01
1,India CX Report'25: Residential Real Estate\n ...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Residential Real Estate cl...,KPMG,2025-03-01
2,India CX Report'25: Real Estate\n \n ...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Real Estate close contact_...,KPMG,2025-03-01
3,India CX Report'25: Premium Hotels\n \n...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Premium Hotels close conta...,KPMG,2025-03-01
4,India CX Report'25: Hotels\n \n ...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Hotels close contact_mail ...,KPMG,2025-03-01
5,India CX Report'25: Budget Hotels\n \n ...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Budget Hotels close contac...,KPMG,2025-03-01
6,India CX Report'25: Consumer Durables\n ...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Consumer Durables close co...,KPMG,2025-03-01
7,India CX Report'25: Small Appliances\n ...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Small Appliances close con...,KPMG,2025-03-01
8,India CX Report'25: Large Appliances\n ...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Large Appliances close con...,KPMG,2025-03-01
9,Evolving third party landscape in India's medi...,https://kpmg.com/in/en/insights/2025/03/evolvi...,Evolving third party landscape in India's medi...,KPMG,2025-03-01
10,Issue no. 104 | March 2025\n \n ...,https://kpmg.com/in/en/insights/2025/03/aau-ac...,Issue no. 104 | March 2025 close contact_mail ...,KPMG,2025-03-01
11,Related party transactions – Minimum informati...,https://kpmg.com/in/en/insights/2025/03/firstn...,Related party transactions – Minimum informati...,KPMG,2025-03-01
12,Third-party risks in the pharmaceutical supply...,https://kpmg.com/in/en/insights/2025/03/third-...,Third-party risks in the pharmaceutical supply...,KPMG,2025-03-01
13,Intelligent retail\n \n Explorin...,https://kpmg.com/in/en/insights/2025/03/intell...,Intelligent retail close contact_mail Contact ...,KPMG,2025-03-01
14,India’s digital transformation provides a blue...,https://kpmg.com/in/en/blogs/2025/03/indias-di...,India’s digital transformation provides a blue...,KPMG,2025-03-01
15,Cybersecurity considerations 2025\n \n ...,https://kpmg.com/in/en/insights/2025/03/cybers...,Cybersecurity considerations 2025 close contac...,KPMG,2025-03-01
16,India CX Report'25: Airlines\n \n ...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Airlines close contact_mai...,KPMG,2025-03-01
17,Mastering intentional experiences: India CX re...,https://kpmg.com/in/en/insights/2025/03/india-...,Mastering intentional experiences: India CX re...,KPMG,2025-03-01
18,Navigating Reserve Bank of India’s guidelines ...,https://kpmg.com/in/en/insights/2025/03/naviga...,Navigating Reserve Bank of India’s guidelines ...,KPMG,2025-03-01
19,"Indian ports are now better, but what’s next?\...",https://kpmg.com/in/en/blogs/2025/03/indian-po...,"Indian ports are now better, but what’s next? ...",KPMG,2025-03-01
20,Innovative strategies for cost optimisation – ...,https://kpmg.com/in/en/blogs/2025/03/innovativ...,Innovative strategies for cost optimisation – ...,KPMG,2025-03-01
21,Aviation\n \n Airlines need to m...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Airlines close contact_mai...,KPMG,2025-03-01
22,Pulse of Fintech: H2 2024\n \n B...,https://kpmg.com/in/en/insights/2025/03/pulse-...,Pulse of Fintech: H2 2024 close contact_mail C...,KPMG,2025-03-01
23,The rise of silver generation: Transforming th...,https://kpmg.com/in/en/insights/2025/03/the-ri...,The rise of silver generation: Transforming th...,KPMG,2025-03-01
24,Aviation leasing and financing ecosystem at GI...,https://kpmg.com/in/en/insights/2025/03/aviati...,Aviation leasing and financing ecosystem at GI...,KPMG,2025-03-01
25,Textile industry embraces sustainability and i...,https://kpmg.com/in/en/blogs/2025/03/textile-i...,Textile industry embraces sustainability and i...,KPMG,2025-03-01

In [74]:
dff = dff[['title','link','content','date','source']]

In [75]:
dff

,title,link,content,date,source
0,India CX Report'25: Commercial Real Estate\n ...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Commercial Real Estate clo...,2025-03-01,KPMG
1,India CX Report'25: Residential Real Estate\n ...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Residential Real Estate cl...,2025-03-01,KPMG
2,India CX Report'25: Real Estate\n \n ...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Real Estate close contact_...,2025-03-01,KPMG
3,India CX Report'25: Premium Hotels\n \n...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Premium Hotels close conta...,2025-03-01,KPMG
4,India CX Report'25: Hotels\n \n ...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Hotels close contact_mail ...,2025-03-01,KPMG
5,India CX Report'25: Budget Hotels\n \n ...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Budget Hotels close contac...,2025-03-01,KPMG
6,India CX Report'25: Consumer Durables\n ...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Consumer Durables close co...,2025-03-01,KPMG
7,India CX Report'25: Small Appliances\n ...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Small Appliances close con...,2025-03-01,KPMG
8,India CX Report'25: Large Appliances\n ...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Large Appliances close con...,2025-03-01,KPMG
9,Evolving third party landscape in India's medi...,https://kpmg.com/in/en/insights/2025/03/evolvi...,Evolving third party landscape in India's medi...,2025-03-01,KPMG
10,Issue no. 104 | March 2025\n \n ...,https://kpmg.com/in/en/insights/2025/03/aau-ac...,Issue no. 104 | March 2025 close contact_mail ...,2025-03-01,KPMG
11,Related party transactions – Minimum informati...,https://kpmg.com/in/en/insights/2025/03/firstn...,Related party transactions – Minimum informati...,2025-03-01,KPMG
12,Third-party risks in the pharmaceutical supply...,https://kpmg.com/in/en/insights/2025/03/third-...,Third-party risks in the pharmaceutical supply...,2025-03-01,KPMG
13,Intelligent retail\n \n Explorin...,https://kpmg.com/in/en/insights/2025/03/intell...,Intelligent retail close contact_mail Contact ...,2025-03-01,KPMG
14,India’s digital transformation provides a blue...,https://kpmg.com/in/en/blogs/2025/03/indias-di...,India’s digital transformation provides a blue...,2025-03-01,KPMG
15,Cybersecurity considerations 2025\n \n ...,https://kpmg.com/in/en/insights/2025/03/cybers...,Cybersecurity considerations 2025 close contac...,2025-03-01,KPMG
16,India CX Report'25: Airlines\n \n ...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Airlines close contact_mai...,2025-03-01,KPMG
17,Mastering intentional experiences: India CX re...,https://kpmg.com/in/en/insights/2025/03/india-...,Mastering intentional experiences: India CX re...,2025-03-01,KPMG
18,Navigating Reserve Bank of India’s guidelines ...,https://kpmg.com/in/en/insights/2025/03/naviga...,Navigating Reserve Bank of India’s guidelines ...,2025-03-01,KPMG
19,"Indian ports are now better, but what’s next?\...",https://kpmg.com/in/en/blogs/2025/03/indian-po...,"Indian ports are now better, but what’s next? ...",2025-03-01,KPMG
20,Innovative strategies for cost optimisation – ...,https://kpmg.com/in/en/blogs/2025/03/innovativ...,Innovative strategies for cost optimisation – ...,2025-03-01,KPMG
21,Aviation\n \n Airlines need to m...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Airlines close contact_mai...,2025-03-01,KPMG
22,Pulse of Fintech: H2 2024\n \n B...,https://kpmg.com/in/en/insights/2025/03/pulse-...,Pulse of Fintech: H2 2024 close contact_mail C...,2025-03-01,KPMG
23,The rise of silver generation: Transforming th...,https://kpmg.com/in/en/insights/2025/03/the-ri...,The rise of silver generation: Transforming th...,2025-03-01,KPMG
24,Aviation leasing and financing ecosystem at GI...,https://kpmg.com/in/en/insights/2025/03/aviati...,Aviation leasing and financing ecosystem at GI...,2025-03-01,KPMG
25,Textile industry embraces sustainability and i...,https://kpmg.com/in/en/blogs/2025/03/textile-i...,Textile industry embraces sustainability and i...,2025-03-01,KPMG

In [76]:
dff2

,title,link,content,date,source
2,Agentic AI in the human capital management (HC...,https://www.pwc.in/ghost-templates/agentic-ai-...,Agentic AI in the human capital management (HC...,2025-03-27,PWC
3,Indian family offices – the new investors for ...,https://www.pwc.in/ghost-templates/indian-fami...,Indian family offices – \nthe new investors fo...,2025-03-26,PWC
4,Intergenerational trust: The key to succession...,https://www.pwc.in/ghost-templates/intergenera...,Intergenerational trust: \nThe key to success...,2025-03-11,PWC
5,Understanding the impact of GenAI on the India...,https://www.pwc.in/ghost-templates/understandi...,March 2024\nIndian healthcare ecosystem \nUnde...,2025-03-10,PWC
6,Quality measures and standards for transitioni...,https://www.pwc.in/ghost-templates/quality-mea...,Quality measures and standards \nMarch 2025\nf...,2025-03-07,PWC
7,The mutual funds route to Viksit Bharat @2047,https://www.pwc.in/ghost-templates/the-mutual-...,The mutual funds route \nto Viksit Bharat @204...,2025-03-05,PWC
8,Financial health: Transcending from access to ...,https://www.pwc.in/ghost-templates/financial-h...,TM\nMarch 2025Financial health: \nTranscendin...,2025-03-04,PWC
9,Towards a climate-resilient future: Strategies...,https://www.pwc.in/ghost-templates/towards-a-c...,Towards a climate-resilient \nfuture: Strategi...,2025-03-04,PWC

In [77]:
combined_df = pd.concat([dff, dff2], ignore_index=True)

In [78]:
combined_df

,title,link,content,date,source
0,India CX Report'25: Commercial Real Estate\n ...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Commercial Real Estate clo...,2025-03-01 00:00:00,KPMG
1,India CX Report'25: Residential Real Estate\n ...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Residential Real Estate cl...,2025-03-01 00:00:00,KPMG
2,India CX Report'25: Real Estate\n \n ...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Real Estate close contact_...,2025-03-01 00:00:00,KPMG
3,India CX Report'25: Premium Hotels\n \n...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Premium Hotels close conta...,2025-03-01 00:00:00,KPMG
4,India CX Report'25: Hotels\n \n ...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Hotels close contact_mail ...,2025-03-01 00:00:00,KPMG
5,India CX Report'25: Budget Hotels\n \n ...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Budget Hotels close contac...,2025-03-01 00:00:00,KPMG
6,India CX Report'25: Consumer Durables\n ...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Consumer Durables close co...,2025-03-01 00:00:00,KPMG
7,India CX Report'25: Small Appliances\n ...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Small Appliances close con...,2025-03-01 00:00:00,KPMG
8,India CX Report'25: Large Appliances\n ...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Large Appliances close con...,2025-03-01 00:00:00,KPMG
9,Evolving third party landscape in India's medi...,https://kpmg.com/in/en/insights/2025/03/evolvi...,Evolving third party landscape in India's medi...,2025-03-01 00:00:00,KPMG
10,Issue no. 104 | March 2025\n \n ...,https://kpmg.com/in/en/insights/2025/03/aau-ac...,Issue no. 104 | March 2025 close contact_mail ...,2025-03-01 00:00:00,KPMG
11,Related party transactions – Minimum informati...,https://kpmg.com/in/en/insights/2025/03/firstn...,Related party transactions – Minimum informati...,2025-03-01 00:00:00,KPMG
12,Third-party risks in the pharmaceutical supply...,https://kpmg.com/in/en/insights/2025/03/third-...,Third-party risks in the pharmaceutical supply...,2025-03-01 00:00:00,KPMG
13,Intelligent retail\n \n Explorin...,https://kpmg.com/in/en/insights/2025/03/intell...,Intelligent retail close contact_mail Contact ...,2025-03-01 00:00:00,KPMG
14,India’s digital transformation provides a blue...,https://kpmg.com/in/en/blogs/2025/03/indias-di...,India’s digital transformation provides a blue...,2025-03-01 00:00:00,KPMG
15,Cybersecurity considerations 2025\n \n ...,https://kpmg.com/in/en/insights/2025/03/cybers...,Cybersecurity considerations 2025 close contac...,2025-03-01 00:00:00,KPMG
16,India CX Report'25: Airlines\n \n ...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Airlines close contact_mai...,2025-03-01 00:00:00,KPMG
17,Mastering intentional experiences: India CX re...,https://kpmg.com/in/en/insights/2025/03/india-...,Mastering intentional experiences: India CX re...,2025-03-01 00:00:00,KPMG
18,Navigating Reserve Bank of India’s guidelines ...,https://kpmg.com/in/en/insights/2025/03/naviga...,Navigating Reserve Bank of India’s guidelines ...,2025-03-01 00:00:00,KPMG
19,"Indian ports are now better, but what’s next?\...",https://kpmg.com/in/en/blogs/2025/03/indian-po...,"Indian ports are now better, but what’s next? ...",2025-03-01 00:00:00,KPMG
20,Innovative strategies for cost optimisation – ...,https://kpmg.com/in/en/blogs/2025/03/innovativ...,Innovative strategies for cost optimisation – ...,2025-03-01 00:00:00,KPMG
21,Aviation\n \n Airlines need to m...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Airlines close contact_mai...,2025-03-01 00:00:00,KPMG
22,Pulse of Fintech: H2 2024\n \n B...,https://kpmg.com/in/en/insights/2025/03/pulse-...,Pulse of Fintech: H2 2024 close contact_mail C...,2025-03-01 00:00:00,KPMG
23,The rise of silver generation: Transforming th...,https://kpmg.com/in/en/insights/2025/03/the-ri...,The rise of silver generation: Transforming th...,2025-03-01 00:00:00,KPMG
24,Aviation leasing and financing ecosystem at GI...,https://kpmg.com/in/en/insights/2025/03/aviati...,Aviation leasing and financing ecosystem at GI...,2025-03-01 00:00:00,KPMG
25,Textile industry embraces sustainability and i...,https://kpmg.com/in/en/blogs/2025/03/textile-i...,Textile industry embraces sustainability and i...,2025-03-01 00:00:00,KPMG
26,Agentic AI in the human capital management (HC...,https://www.pwc.in/ghost-templates/agentic-ai-...,Agentic AI in the human capital management (HC...,2025-03-27,PWC
27,Indian family offices – the new investors for ...,https://www.pwc.in/ghost-templates/indian-fami...,Indian family offices – \nthe new investors fo...,2025-03-26,PWC
28,Intergenerational trust: The key to succession...,https://www.pwc.in/ghost-templates/intergenera...,Intergenerational trust: \nThe key to success...,2025-03-11,PWC
29,Understanding the impact of GenAI on the India...,https://www.pwc.in/ghost-templates/understandi...,March 2024\nIndian healthcare ecosystem \nUnde...,2025-03-10,PWC
30,Quality measures and standards for transitioni...,https://www.pwc.in/ghost-templates/quality-mea...,Quality measures and standards \nMarch 2025\nf...,2025-03-07,PWC
31,The mutual funds route to Viksit Bharat @2047,https://www.pwc.in/ghost-templates/the-mutual-...,The mutual funds route \nto Viksit Bharat @204...,2025-03-05,PWC
32,Financial health: Transcending from access to ...,https://www.pwc.in/ghost-templates/financial-h...,TM\nMarch 2025Financial health: \nTranscendin...,2025-03-04,PWC
33,Towards a climate-resilient future: Strategies...,https://www.pwc.in/ghost-templates/towards-a-c...,Towards a climate-resilient \nfuture: Strategi...,2025-03-04,PWC

In [79]:
combined_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34 entries, 0 to 33
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   title    34 non-null     object
 1   link     34 non-null     object
 2   content  34 non-null     object
 3   date     34 non-null     object
 4   source   34 non-null     object
dtypes: object(5)
memory usage: 1.5+ KB

## Pre-processing

##### Removing spaecs and punctuations

In [82]:
def preprocess(text):
    text = re.sub(r'\s+', ' ', str(text))          # Remove extra spaces/newlines
    text = re.sub(r'[^\w\s]', '', text)            # Remove punctuation
    text = text.lower().strip()                    # Lowercase and strip
    return text

In [83]:
combined_df['clean_content'] = combined_df['content'].apply(preprocess)

In [84]:
combined_df

,title,link,content,date,source,clean_content
0,India CX Report'25: Commercial Real Estate\n ...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Commercial Real Estate clo...,2025-03-01 00:00:00,KPMG,india cx report25 commercial real estate close...
1,India CX Report'25: Residential Real Estate\n ...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Residential Real Estate cl...,2025-03-01 00:00:00,KPMG,india cx report25 residential real estate clos...
2,India CX Report'25: Real Estate\n \n ...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Real Estate close contact_...,2025-03-01 00:00:00,KPMG,india cx report25 real estate close contact_ma...
3,India CX Report'25: Premium Hotels\n \n...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Premium Hotels close conta...,2025-03-01 00:00:00,KPMG,india cx report25 premium hotels close contact...
4,India CX Report'25: Hotels\n \n ...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Hotels close contact_mail ...,2025-03-01 00:00:00,KPMG,india cx report25 hotels close contact_mail co...
5,India CX Report'25: Budget Hotels\n \n ...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Budget Hotels close contac...,2025-03-01 00:00:00,KPMG,india cx report25 budget hotels close contact_...
6,India CX Report'25: Consumer Durables\n ...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Consumer Durables close co...,2025-03-01 00:00:00,KPMG,india cx report25 consumer durables close cont...
7,India CX Report'25: Small Appliances\n ...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Small Appliances close con...,2025-03-01 00:00:00,KPMG,india cx report25 small appliances close conta...
8,India CX Report'25: Large Appliances\n ...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Large Appliances close con...,2025-03-01 00:00:00,KPMG,india cx report25 large appliances close conta...
9,Evolving third party landscape in India's medi...,https://kpmg.com/in/en/insights/2025/03/evolvi...,Evolving third party landscape in India's medi...,2025-03-01 00:00:00,KPMG,evolving third party landscape in indias media...
10,Issue no. 104 | March 2025\n \n ...,https://kpmg.com/in/en/insights/2025/03/aau-ac...,Issue no. 104 | March 2025 close contact_mail ...,2025-03-01 00:00:00,KPMG,issue no 104 march 2025 close contact_mail co...
11,Related party transactions – Minimum informati...,https://kpmg.com/in/en/insights/2025/03/firstn...,Related party transactions – Minimum informati...,2025-03-01 00:00:00,KPMG,related party transactions minimum informatio...
12,Third-party risks in the pharmaceutical supply...,https://kpmg.com/in/en/insights/2025/03/third-...,Third-party risks in the pharmaceutical supply...,2025-03-01 00:00:00,KPMG,thirdparty risks in the pharmaceutical supply ...
13,Intelligent retail\n \n Explorin...,https://kpmg.com/in/en/insights/2025/03/intell...,Intelligent retail close contact_mail Contact ...,2025-03-01 00:00:00,KPMG,intelligent retail close contact_mail contact ...
14,India’s digital transformation provides a blue...,https://kpmg.com/in/en/blogs/2025/03/indias-di...,India’s digital transformation provides a blue...,2025-03-01 00:00:00,KPMG,indias digital transformation provides a bluep...
15,Cybersecurity considerations 2025\n \n ...,https://kpmg.com/in/en/insights/2025/03/cybers...,Cybersecurity considerations 2025 close contac...,2025-03-01 00:00:00,KPMG,cybersecurity considerations 2025 close contac...
16,India CX Report'25: Airlines\n \n ...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Airlines close contact_mai...,2025-03-01 00:00:00,KPMG,india cx report25 airlines close contact_mail ...
17,Mastering intentional experiences: India CX re...,https://kpmg.com/in/en/insights/2025/03/india-...,Mastering intentional experiences: India CX re...,2025-03-01 00:00:00,KPMG,mastering intentional experiences india cx rep...
18,Navigating Reserve Bank of India’s guidelines ...,https://kpmg.com/in/en/insights/2025/03/naviga...,Navigating Reserve Bank of India’s guidelines ...,2025-03-01 00:00:00,KPMG,navigating reserve bank of indias guidelines f...
19,"Indian ports are now better, but what’s next?\...",https://kpmg.com/in/en/blogs/2025/03/indian-po...,"Indian ports are now better, but what’s next? ...",2025-03-01 00:00:00,KPMG,indian ports are now better but whats next clo...
20,Innovative strategies for cost optimisation – ...,https://kpmg.com/in/en/blogs/2025/03/innovativ...,Innovative strategies for cost optimisation – ...,2025-03-01 00:00:00,KPMG,innovative strategies for cost optimisation a...
21,Aviation\n \n Airlines need to m...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Airlines close contact_mai...,2025-03-01 00:00:00,KPMG,india cx report25 airlines close contact_mail ...
22,Pulse of Fintech: H2 2024\n \n B...,https://kpmg.com/in/en/insights/2025/03/pulse-...,Pulse of Fintech: H2 2024 close contact_mail C...,2025-03-01 00:00:00,KPMG,pulse of fintech h2 2024 close contact_mail co...
23,The rise of silver generation: Transforming th...,https://kpmg.com/in/en/insights/2025/03/the-ri...,The rise of silver generation: Transforming th...,2025-03-01 00:00:00,KPMG,the rise of silver generation transforming the...
24,Aviation leasing and financing ecosystem at GI...,https://kpmg.com/in/en/insights/2025/03/aviati...,Aviation leasing and financing ecosystem at GI...,2025-03-01 00:00:00,KPMG,aviation leasing and financing ecosystem at gi...
25,Textile industry embraces sustainability and i...,https://kpmg.com/in/en/blogs/2025/03/textile-i...,Textile industry embraces sustainability and i...,2025-03-01 00:00:00,KPMG,textile industry embraces sustainability and i...
26,Agentic AI in the human capital management (HC...,https://www.pwc.in/ghost-templates/agentic-ai-...,Agentic AI in the human capital management (HC...,2025-03-27,PWC,agentic ai in the human capital management hcm...
27,Indian family offices – the new investors for ...,https://www.pwc.in/ghost-templates/indian-fami...,Indian family offices – \nthe new investors fo...,2025-03-26,PWC,indian family offices the new investors for i...
28,Intergenerational trust: The key to succession...,https://www.pwc.in/ghost-templates/intergenera...,Intergenerational trust: \nThe key to success...,2025-03-11,PWC,intergenerational trust the key to succession ...
29,Understanding the impact of GenAI on the India...,https://www.pwc.in/ghost-templates/understandi...,March 2024\nIndian healthcare ecosystem \nUnde...,2025-03-10,PWC,march 2024 indian healthcare ecosystem underst...
30,Quality measures and standards for transitioni...,https://www.pwc.in/ghost-templates/quality-mea...,Quality measures and standards \nMarch 2025\nf...,2025-03-07,PWC,quality measures and standards march 2025 for ...
31,The mutual funds route to Viksit Bharat @2047,https://www.pwc.in/ghost-templates/the-mutual-...,The mutual funds route \nto Viksit Bharat @204...,2025-03-05,PWC,the mutual funds route to viksit bharat 2047 t...
32,Financial health: Transcending from access to ...,https://www.pwc.in/ghost-templates/financial-h...,TM\nMarch 2025Financial health: \nTranscendin...,2025-03-04,PWC,tm march 2025financial health transcending fro...
33,Towards a climate-resilient future: Strategies...,https://www.pwc.in/ghost-templates/towards-a-c...,Towards a climate-resilient \nfuture: Strategi...,2025-03-04,PWC,towards a climateresilient future strategies f...

##### Adding content length

In [ ]:
combined_df['content_length'] = combined_df['clean_content'].apply(lambda x: len(str(x)))

In [86]:
combined_df

,title,link,content,date,source,clean_content,content_length
0,India CX Report'25: Commercial Real Estate\n ...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Commercial Real Estate clo...,2025-03-01 00:00:00,KPMG,india cx report25 commercial real estate close...,14257
1,India CX Report'25: Residential Real Estate\n ...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Residential Real Estate cl...,2025-03-01 00:00:00,KPMG,india cx report25 residential real estate clos...,14209
2,India CX Report'25: Real Estate\n \n ...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Real Estate close contact_...,2025-03-01 00:00:00,KPMG,india cx report25 real estate close contact_ma...,7291
3,India CX Report'25: Premium Hotels\n \n...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Premium Hotels close conta...,2025-03-01 00:00:00,KPMG,india cx report25 premium hotels close contact...,14085
4,India CX Report'25: Hotels\n \n ...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Hotels close contact_mail ...,2025-03-01 00:00:00,KPMG,india cx report25 hotels close contact_mail co...,7531
5,India CX Report'25: Budget Hotels\n \n ...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Budget Hotels close contac...,2025-03-01 00:00:00,KPMG,india cx report25 budget hotels close contact_...,13251
6,India CX Report'25: Consumer Durables\n ...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Consumer Durables close co...,2025-03-01 00:00:00,KPMG,india cx report25 consumer durables close cont...,7228
7,India CX Report'25: Small Appliances\n ...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Small Appliances close con...,2025-03-01 00:00:00,KPMG,india cx report25 small appliances close conta...,11648
8,India CX Report'25: Large Appliances\n ...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Large Appliances close con...,2025-03-01 00:00:00,KPMG,india cx report25 large appliances close conta...,11079
9,Evolving third party landscape in India's medi...,https://kpmg.com/in/en/insights/2025/03/evolvi...,Evolving third party landscape in India's medi...,2025-03-01 00:00:00,KPMG,evolving third party landscape in indias media...,5219
10,Issue no. 104 | March 2025\n \n ...,https://kpmg.com/in/en/insights/2025/03/aau-ac...,Issue no. 104 | March 2025 close contact_mail ...,2025-03-01 00:00:00,KPMG,issue no 104 march 2025 close contact_mail co...,4755
11,Related party transactions – Minimum informati...,https://kpmg.com/in/en/insights/2025/03/firstn...,Related party transactions – Minimum informati...,2025-03-01 00:00:00,KPMG,related party transactions minimum informatio...,4240
12,Third-party risks in the pharmaceutical supply...,https://kpmg.com/in/en/insights/2025/03/third-...,Third-party risks in the pharmaceutical supply...,2025-03-01 00:00:00,KPMG,thirdparty risks in the pharmaceutical supply ...,6631
13,Intelligent retail\n \n Explorin...,https://kpmg.com/in/en/insights/2025/03/intell...,Intelligent retail close contact_mail Contact ...,2025-03-01 00:00:00,KPMG,intelligent retail close contact_mail contact ...,5733
14,India’s digital transformation provides a blue...,https://kpmg.com/in/en/blogs/2025/03/indias-di...,India’s digital transformation provides a blue...,2025-03-01 00:00:00,KPMG,indias digital transformation provides a bluep...,8912
15,Cybersecurity considerations 2025\n \n ...,https://kpmg.com/in/en/insights/2025/03/cybers...,Cybersecurity considerations 2025 close contac...,2025-03-01 00:00:00,KPMG,cybersecurity considerations 2025 close contac...,6845
16,India CX Report'25: Airlines\n \n ...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Airlines close contact_mai...,2025-03-01 00:00:00,KPMG,india cx report25 airlines close contact_mail ...,12040
17,Mastering intentional experiences: India CX re...,https://kpmg.com/in/en/insights/2025/03/india-...,Mastering intentional experiences: India CX re...,2025-03-01 00:00:00,KPMG,mastering intentional experiences india cx rep...,10093
18,Navigating Reserve Bank of India’s guidelines ...,https://kpmg.com/in/en/insights/2025/03/naviga...,Navigating Reserve Bank of India’s guidelines ...,2025-03-01 00:00:00,KPMG,navigating reserve bank of indias guidelines f...,4673
19,"Indian ports are now better, but what’s next?\...",https://kpmg.com/in/en/blogs/2025/03/indian-po...,"Indian ports are now better, but what’s next? ...",2025-03-01 00:00:00,KPMG,indian ports are now better but whats next clo...,10998
20,Innovative strategies for cost optimisation – ...,https://kpmg.com/in/en/blogs/2025/03/innovativ...,Innovative strategies for cost optimisation – ...,2025-03-01 00:00:00,KPMG,innovative strategies for cost optimisation a...,8902
21,Aviation\n \n Airlines need to m...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Airlines close contact_mai...,2025-03-01 00:00:00,KPMG,india cx report25 airlines close contact_mail ...,12040
22,Pulse of Fintech: H2 2024\n \n B...,https://kpmg.com/in/en/insights/2025/03/pulse-...,Pulse of Fintech: H2 2024 close contact_mail C...,2025-03-01 00:00:00,KPMG,pulse of fintech h2 2024 close contact_mail co...,5893
23,The rise of silver generation: Transforming th...,https://kpmg.com/in/en/insights/2025/03/the-ri...,The rise of silver generation: Transforming th...,2025-03-01 00:00:00,KPMG,the rise of silver generation transforming the...,7094
24,Aviation leasing and financing ecosystem at GI...,https://kpmg.com/in/en/insights/2025/03/aviati...,Aviation leasing and financing ecosystem at GI...,2025-03-01 00:00:00,KPMG,aviation leasing and financing ecosystem at gi...,7143
25,Textile industry embraces sustainability and i...,https://kpmg.com/in/en/blogs/2025/03/textile-i...,Textile industry embraces sustainability and i...,2025-03-01 00:00:00,KPMG,textile industry embraces sustainability and i...,5415
26,Agentic AI in the human capital management (HC...,https://www.pwc.in/ghost-templates/agentic-ai-...,Agentic AI in the human capital management (HC...,2025-03-27,PWC,agentic ai in the human capital management hcm...,4969
27,Indian family offices – the new investors for ...,https://www.pwc.in/ghost-templates/indian-fami...,Indian family offices – \nthe new investors fo...,2025-03-26,PWC,indian family offices the new investors for i...,18135
28,Intergenerational trust: The key to succession...,https://www.pwc.in/ghost-templates/intergenera...,Intergenerational trust: \nThe key to success...,2025-03-11,PWC,intergenerational trust the key to succession ...,14649
29,Understanding the impact of GenAI on the India...,https://www.pwc.in/ghost-templates/understandi...,March 2024\nIndian healthcare ecosystem \nUnde...,2025-03-10,PWC,march 2024 indian healthcare ecosystem underst...,94243
30,Quality measures and standards for transitioni...,https://www.pwc.in/ghost-templates/quality-mea...,Quality measures and standards \nMarch 2025\nf...,2025-03-07,PWC,quality measures and standards march 2025 for ...,93103
31,The mutual funds route to Viksit Bharat @2047,https://www.pwc.in/ghost-templates/the-mutual-...,The mutual funds route \nto Viksit Bharat @204...,2025-03-05,PWC,the mutual funds route to viksit bharat 2047 t...,116681
32,Financial health: Transcending from access to ...,https://www.pwc.in/ghost-templates/financial-h...,TM\nMarch 2025Financial health: \nTranscendin...,2025-03-04,PWC,tm march 2025financial health transcending fro...,31576
33,Towards a climate-resilient future: Strategies...,https://www.pwc.in/ghost-templates/towards-a-c...,Towards a climate-resilient \nfuture: Strategi...,2025-03-04,PWC,towards a climateresilient future strategies f...,113941

In [91]:
combined_df

,title,link,content,date,source,clean_content,content_length
0,India CX Report'25: Commercial Real Estate\n ...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Commercial Real Estate clo...,2025-03-01 00:00:00,KPMG,india cx report25 commercial real estate close...,14257
1,India CX Report'25: Residential Real Estate\n ...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Residential Real Estate cl...,2025-03-01 00:00:00,KPMG,india cx report25 residential real estate clos...,14209
2,India CX Report'25: Real Estate\n \n ...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Real Estate close contact_...,2025-03-01 00:00:00,KPMG,india cx report25 real estate close contact_ma...,7291
3,India CX Report'25: Premium Hotels\n \n...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Premium Hotels close conta...,2025-03-01 00:00:00,KPMG,india cx report25 premium hotels close contact...,14085
4,India CX Report'25: Hotels\n \n ...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Hotels close contact_mail ...,2025-03-01 00:00:00,KPMG,india cx report25 hotels close contact_mail co...,7531
5,India CX Report'25: Budget Hotels\n \n ...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Budget Hotels close contac...,2025-03-01 00:00:00,KPMG,india cx report25 budget hotels close contact_...,13251
6,India CX Report'25: Consumer Durables\n ...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Consumer Durables close co...,2025-03-01 00:00:00,KPMG,india cx report25 consumer durables close cont...,7228
7,India CX Report'25: Small Appliances\n ...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Small Appliances close con...,2025-03-01 00:00:00,KPMG,india cx report25 small appliances close conta...,11648
8,India CX Report'25: Large Appliances\n ...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Large Appliances close con...,2025-03-01 00:00:00,KPMG,india cx report25 large appliances close conta...,11079
9,Evolving third party landscape in India's medi...,https://kpmg.com/in/en/insights/2025/03/evolvi...,Evolving third party landscape in India's medi...,2025-03-01 00:00:00,KPMG,evolving third party landscape in indias media...,5219
10,Issue no. 104 | March 2025\n \n ...,https://kpmg.com/in/en/insights/2025/03/aau-ac...,Issue no. 104 | March 2025 close contact_mail ...,2025-03-01 00:00:00,KPMG,issue no 104 march 2025 close contact_mail co...,4755
11,Related party transactions – Minimum informati...,https://kpmg.com/in/en/insights/2025/03/firstn...,Related party transactions – Minimum informati...,2025-03-01 00:00:00,KPMG,related party transactions minimum informatio...,4240
12,Third-party risks in the pharmaceutical supply...,https://kpmg.com/in/en/insights/2025/03/third-...,Third-party risks in the pharmaceutical supply...,2025-03-01 00:00:00,KPMG,thirdparty risks in the pharmaceutical supply ...,6631
13,Intelligent retail\n \n Explorin...,https://kpmg.com/in/en/insights/2025/03/intell...,Intelligent retail close contact_mail Contact ...,2025-03-01 00:00:00,KPMG,intelligent retail close contact_mail contact ...,5733
14,India’s digital transformation provides a blue...,https://kpmg.com/in/en/blogs/2025/03/indias-di...,India’s digital transformation provides a blue...,2025-03-01 00:00:00,KPMG,indias digital transformation provides a bluep...,8912
15,Cybersecurity considerations 2025\n \n ...,https://kpmg.com/in/en/insights/2025/03/cybers...,Cybersecurity considerations 2025 close contac...,2025-03-01 00:00:00,KPMG,cybersecurity considerations 2025 close contac...,6845
16,India CX Report'25: Airlines\n \n ...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Airlines close contact_mai...,2025-03-01 00:00:00,KPMG,india cx report25 airlines close contact_mail ...,12040
17,Mastering intentional experiences: India CX re...,https://kpmg.com/in/en/insights/2025/03/india-...,Mastering intentional experiences: India CX re...,2025-03-01 00:00:00,KPMG,mastering intentional experiences india cx rep...,10093
18,Navigating Reserve Bank of India’s guidelines ...,https://kpmg.com/in/en/insights/2025/03/naviga...,Navigating Reserve Bank of India’s guidelines ...,2025-03-01 00:00:00,KPMG,navigating reserve bank of indias guidelines f...,4673
19,"Indian ports are now better, but what’s next?\...",https://kpmg.com/in/en/blogs/2025/03/indian-po...,"Indian ports are now better, but what’s next? ...",2025-03-01 00:00:00,KPMG,indian ports are now better but whats next clo...,10998
20,Innovative strategies for cost optimisation – ...,https://kpmg.com/in/en/blogs/2025/03/innovativ...,Innovative strategies for cost optimisation – ...,2025-03-01 00:00:00,KPMG,innovative strategies for cost optimisation a...,8902
21,Aviation\n \n Airlines need to m...,https://kpmg.com/in/en/insights/2025/03/india-...,India CX Report'25: Airlines close contact_mai...,2025-03-01 00:00:00,KPMG,india cx report25 airlines close contact_mail ...,12040
22,Pulse of Fintech: H2 2024\n \n B...,https://kpmg.com/in/en/insights/2025/03/pulse-...,Pulse of Fintech: H2 2024 close contact_mail C...,2025-03-01 00:00:00,KPMG,pulse of fintech h2 2024 close contact_mail co...,5893
23,The rise of silver generation: Transforming th...,https://kpmg.com/in/en/insights/2025/03/the-ri...,The rise of silver generation: Transforming th...,2025-03-01 00:00:00,KPMG,the rise of silver generation transforming the...,7094
24,Aviation leasing and financing ecosystem at GI...,https://kpmg.com/in/en/insights/2025/03/aviati...,Aviation leasing and financing ecosystem at GI...,2025-03-01 00:00:00,KPMG,aviation leasing and financing ecosystem at gi...,7143
25,Textile industry embraces sustainability and i...,https://kpmg.com/in/en/blogs/2025/03/textile-i...,Textile industry embraces sustainability and i...,2025-03-01 00:00:00,KPMG,textile industry embraces sustainability and i...,5415
26,Agentic AI in the human capital management (HC...,https://www.pwc.in/ghost-templates/agentic-ai-...,Agentic AI in the human capital management (HC...,2025-03-27,PWC,agentic ai in the human capital management hcm...,4969
27,Indian family offices – the new investors for ...,https://www.pwc.in/ghost-templates/indian-fami...,Indian family offices – \nthe new investors fo...,2025-03-26,PWC,indian family offices the new investors for i...,18135
28,Intergenerational trust: The key to succession...,https://www.pwc.in/ghost-templates/intergenera...,Intergenerational trust: \nThe key to success...,2025-03-11,PWC,intergenerational trust the key to succession ...,14649
29,Understanding the impact of GenAI on the India...,https://www.pwc.in/ghost-templates/understandi...,March 2024\nIndian healthcare ecosystem \nUnde...,2025-03-10,PWC,march 2024 indian healthcare ecosystem underst...,94243
30,Quality measures and standards for transitioni...,https://www.pwc.in/ghost-templates/quality-mea...,Quality measures and standards \nMarch 2025\nf...,2025-03-07,PWC,quality measures and standards march 2025 for ...,93103
31,The mutual funds route to Viksit Bharat @2047,https://www.pwc.in/ghost-templates/the-mutual-...,The mutual funds route \nto Viksit Bharat @204...,2025-03-05,PWC,the mutual funds route to viksit bharat 2047 t...,116681
32,Financial health: Transcending from access to ...,https://www.pwc.in/ghost-templates/financial-h...,TM\nMarch 2025Financial health: \nTranscendin...,2025-03-04,PWC,tm march 2025financial health transcending fro...,31576
33,Towards a climate-resilient future: Strategies...,https://www.pwc.in/ghost-templates/towards-a-c...,Towards a climate-resilient \nfuture: Strategi...,2025-03-04,PWC,towards a climateresilient future strategies f...,113941

In [93]:
output_path = "cleaned_data/combined_insights_data.csv"
combined_df.to_csv(output_path, index=False)

In [ ]:
output_path = "cleaned_data/combined_insights_data..xlsx"
combined_df.to_excel(output_path, index=False)